### ISSUE TITLE
Fullscreen issue on orientation change

### ISSUE THREAD

**Issue by sankalp123** [zype/zype-android#3]
On orientation change video is not going in full screen mode. It is taking half of the screen.

**Comment by svetdev** [comment]
Thanks for reporting, it seems like it came from the latest Android operating system. We will take a look and will provide an update next week.

**Comment by sankalp123** [comment]
Hi is it resolved?

**Comment by svetdev** [comment]
Hi, we've identified that the issue only occurs if you use templateDebug flavor in build variants, it doesn't happened in zypeDebug. Current solution is to switch to zypeDebug and modify keys to your property.
We are still looking into the full solution and what is different between two versions.

**Comment by svetdev** [comment]
The issue was related to styles in the Dark theme. It should be resolved with the latest commit. @sankalp123 please try and let us know if it works.
