### ISSUE TITLE
Not Able to run this repo source code

### ISSUE THREAD

**Issue by BseAdmin** [zype/zype-android#6]
Hi, 
    I have taken clone and run this updated code but i am getting errors it is not executable code,
please have a look this for error:
http://prntscr.com/irng8t
http://prntscr.com/irnjj0

please have a look thanks

**Comment by svetdev** [comment]
Hi, @BseAdmin You can either replace the values that are left as a placeholders or you can switch to a different Flavor that is preconfigured to work with Zype template.

**Comment by ech89899** [comment]
@BseAdmin 
Just in addition to @svetdev answer:
- Use `zype` flavor to build Zype demo app
- Use `template` flavor to build your own app. In this case you need to replace values in all placeholders for success build.
