### ISSUE TITLE
Can't Run the build...

### ISSUE THREAD

**Issue by jaakkoma** [zype/zype-android#8]
Hi! I'm having a cpl issues with trying to run the Android version of the app. The building seems to work fine. Just Running the tasks while trying to simulate causes these issues. It seems to have something to do with the threadpoolexcecutor.

There's also a warning about the Android SDK version as well as a mysterious "boolean cannot be converted to a string" warning for Native subscription only. It doesn't give it on any of the other options even though I formatted the flags similarily.

Can you help me please?

![screen shot 2018-04-23 at 9 29 53 pm](https://user-images.githubusercontent.com/38677505/39166249-9241310a-473d-11e8-91fe-4af47c2cae07.png)
![screen shot 2018-04-23 at 9 29 42 pm](https://user-images.githubusercontent.com/38677505/39166253-93940c4e-473d-11e8-874e-c7b2d651b9af.png)
![screen shot 2018-04-23 at 9 33 14 pm](https://user-images.githubusercontent.com/38677505/39166349-fffdb196-473d-11e8-80e7-06395aae87bf.png)
![screen shot 2018-04-23 at 9 33 14 pm](https://user-images.githubusercontent.com/38677505/39166364-17b3190c-473e-11e8-8fbd-5f1b50953a67.png)

I've tried doing it all from scratch a cpl times, but the same issue keeps happening. I'm pretty new to all this stuff, so I'm sure it's some stupid little mistake on my end.

**Comment by ech89899** [comment]
Hi @jaakkoma ,
I wasn't able to repeat your issue.
Did you make any changes in the original source code?
Try to clone the project from scratch [this guide](https://github.com/zype/zype-android/blob/master/RECIPE.md).

**Comment by jaakkoma** [comment]
Hi! I was eventually able to get it working: there was an issue with a colors.xml file..

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="accent"><BRAND_COLOR></BRAND_COLOR></color>
</resources>

I had to add the tag closer for the <BRAND_COLOR> tag. Doesn't seem right, but at least the build went through. 

I'm still having issues though... The APK will launch but after the first splash screen it will shut down. On physical phones, on simulated phones etc. I've tried it with a fresh install with no changes to the code (except that brand color thing). I've tried with my API keys from admin.zype.com as well as just having nothing there.  Attached is also the debugging report.

Please help!

[debugging.pdf](https://github.com/zype/zype-android/files/1963554/debugging.pdf)

**Comment by jaakkoma** [comment]
Thank you! Got it working!!

**Comment by ShehanMadushanka** [comment]
> Make sure you have made following updates:
> 
> 1. [ZypeSettings.java](https://github.com/zype/zype-android/blob/master/app/src/template/java/com/zype/android/ZypeSettings.java)  - replace all `<...>` placeholder. Fore API_KEY, CLIENT_ID, CLIENT_SECRET and ROOT_PLAYLIST_ID use respective values from your Zype admin. And for monetization and feature flags use `true` or `false`.
> 2. [build.gradle](https://github.com/zype/zype-android/blob/master/app/build.gradle) - replace `<APPLICATION_ID>` placeholder with your app package name.
> 3. [strings.xml](https://github.com/zype/zype-android/blob/master/app/src/template/res/values/strings.xml) - update your app name.
> 4. [colors.xml](https://github.com/zype/zype-android/blob/master/app/src/template/res/values/colors.xml) and [values-night/colors.xml](https://github.com/zype/zype-android/blob/master/app/src/template/res/values-night/colors.xml) update `<BRAND_COLOR>` with your app color. It should be in `#RRGGBB` format.
> 
> After these updates you should be able to build and run you app successfully.

Can you please mention how to get API_KEY, CLIENT_ID, CLIENT_SECRET and ROOT_PLAYLIST_ID? Do I need a registered zype plan to have them? I just need to see how to use this app.
